clear all;
close all;
clc;

%% MuJoCo -> SE(3) control-frame transformation
R_skydio_control = rotz(45) * roty(180);

%% Rotor positions expressed in the MuJoCo body frame
rotors_mujoco = [ ...
    -0.14, -0.18, 0.05;
    -0.14,  0.18, 0.05;
     0.14,  0.18, 0.08;
     0.14, -0.18, 0.08]';

number_of_configurations = 3;
axis_length = 0.22;

configuration_colors = lines(number_of_configurations);
rotor_colors = lines(4);

figure('Color', 'w', 'Position', [100, 100, 1400, 650]);

tiledlayout(1, 2, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

mujoco_plot = nexttile;
hold(mujoco_plot, 'on');
grid(mujoco_plot, 'on');
axis(mujoco_plot, 'equal');
view(mujoco_plot, 3);
xlabel(mujoco_plot, '$x_M$', 'Interpreter', 'latex');
ylabel(mujoco_plot, '$y_M$', 'Interpreter', 'latex');
zlabel(mujoco_plot, '$z_M$', 'Interpreter', 'latex');
title(mujoco_plot, 'MuJoCo coordinates');

control_plot = nexttile;
hold(control_plot, 'on');
grid(control_plot, 'on');
axis(control_plot, 'equal');
view(control_plot, 3);
xlabel(control_plot, '$x_C$', 'Interpreter', 'latex');
ylabel(control_plot, '$y_C$', 'Interpreter', 'latex');
zlabel(control_plot, '$z_C$', 'Interpreter', 'latex');
title(control_plot, 'SE(3) control coordinates');

%% Generate and plot paired random configurations
for configuration_index = 1:number_of_configurations

    % Random MuJoCo pose
    R_mujoco = quat2rotm(randrot);
    x_mujoco = 2 * rand(3, 1) - 1;

    % Convert the complete pose to the control convention
    x_control = R_skydio_control * x_mujoco;

    R_control = ...
        R_skydio_control * ...
        R_mujoco * ...
        R_skydio_control';

    % Rotor coordinates in the control body frame
    rotors_control = R_skydio_control * rotors_mujoco;

    plotDrone( ...
        mujoco_plot, ...
        x_mujoco, ...
        R_mujoco, ...
        rotors_mujoco, ...
        axis_length, ...
        configuration_colors(configuration_index, :), ...
        rotor_colors, ...
        configuration_index);
    
    plotDrone( ...
        control_plot, ...
        x_control, ...
        R_control, ...
        rotors_control, ...
        axis_length, ...
        configuration_colors(configuration_index, :), ...
        rotor_colors, ...
        configuration_index);
end

%% Use identical limits to make visual comparison easier
all_limits = [-2, 2];

xlim(mujoco_plot, all_limits);
ylim(mujoco_plot, all_limits);
zlim(mujoco_plot, all_limits);

xlim(control_plot, all_limits);
ylim(control_plot, all_limits);
zlim(control_plot, all_limits);

sgtitle('MuJoCo to SE(3) control-frame rotation check');


%% Local plotting function
function plotDrone(axes_handle, position, rotation, rotors_body, ...
                   axis_length, body_color, rotor_colors, ...
                   configuration_index)

    % Rotor positions expressed in world coordinates
    rotors_world = position + rotation * rotors_body;

    % Body center
    scatter3(axes_handle, ...
        position(1), position(2), position(3), ...
        45, body_color, 'filled');

    % Configuration number
    label_offset = [0.04; 0.04; 0.08];

    text(axes_handle, ...
        position(1) + label_offset(1), ...
        position(2) + label_offset(2), ...
        position(3) + label_offset(3), ...
        sprintf('\\bf%d', configuration_index), ...
        'Color', body_color, ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'bottom');

    % Arms and rotors
    for rotor_index = 1:4
        plot3(axes_handle, ...
            [position(1), rotors_world(1, rotor_index)], ...
            [position(2), rotors_world(2, rotor_index)], ...
            [position(3), rotors_world(3, rotor_index)], ...
            '-', ...
            'Color', body_color, ...
            'LineWidth', 1.5);

        scatter3(axes_handle, ...
            rotors_world(1, rotor_index), ...
            rotors_world(2, rotor_index), ...
            rotors_world(3, rotor_index), ...
            35, rotor_colors(rotor_index, :), 'filled');
    end

    % Body axes expressed in world coordinates
    body_x = rotation(:, 1);
    body_y = rotation(:, 2);
    body_z = rotation(:, 3);

    quiver3(axes_handle, ...
        position(1), position(2), position(3), ...
        axis_length * body_x(1), ...
        axis_length * body_x(2), ...
        axis_length * body_x(3), ...
        0, 'r', 'LineWidth', 1.5);

    quiver3(axes_handle, ...
        position(1), position(2), position(3), ...
        axis_length * body_y(1), ...
        axis_length * body_y(2), ...
        axis_length * body_y(3), ...
        0, 'g', 'LineWidth', 1.5);

    quiver3(axes_handle, ...
        position(1), position(2), position(3), ...
        axis_length * body_z(1), ...
        axis_length * body_z(2), ...
        axis_length * body_z(3), ...
        0, 'b', 'LineWidth', 1.5);

end